### ISSUE TITLE
`eth_getCode` and `eth_getStorageAt` unable to deal with non-EVM actors

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc-monorepo#506]
These methods currently return errors if they're called on non-EVM actors (e.g. accounts or else). Instead, they should return empty success responses. See Lotus:

https://github.com/filecoin-project/lotus/blob/b0bc4a96320942c0673a3cab08314074edf4b4f9/node/impl/full/eth.go#L450

**Comment by raulk** [comment]
This requires us to fetch the actor CID and compare it against the builtin-actors registry in the system actor to derive the kind of actor the user has requested. I have a half-cooked branch that adds Fendermint support for doing this correctly. However, in the meantime, to unblock users, I propose we simply return empty responses on ANY error.

**Comment by aakoshh** [comment]
Here are steps to reproduce:


Launch a single Fendermint node:

```bash
cd fendermint/fendermint/testing/smoke-test
cargo make setup
```

In another terminal, clone the Fluence repository:

```bash
cd fluence
git clone https://github.com/fluencelabs/deal -b test-ipc
cd deal
git submodule update --init --recursive
```

Create a `.env` file with the private key from one of the Ethereum accounts which were added to `genesis.json`:

```bash
cat << EOF > .env
PRIVATE_KEY=0x$(cat ../../ipc-monorepo/fendermint/fendermint/testing/smoke-test/test-data/keys/eric-eth.sk)
EOF
```

Try to deploy:

```bash
make deploy-local-ipc
```

```
$ make deploy-local-ipc
...

2024-01-04T13:05:36.741114Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0xa915ea7780d80adb0c4595952a2dbe115e4fe504, 
(code: 22, message: message failed with backtrace:
00: f0105 (method 3) -- invalid method: 3 (22)
, data: None)) address=0xa915ea7780d80adb0c4595952a2dbe115e4fe504
Error: 
Failed to get account for 0xa915ea7780d80adb0c4595952a2dbe115e4fe504: 0xa915ea7780d80adb0c4595952a2dbe115e4fe504
make: *** [Makefile:45: deploy-local-ipc] Error 1
```

**Comment by raulk** [comment]
Will push my unfinished branch in the next hours to solve this for real.

**Comment by aakoshh** [comment]
Okay thanks! 

I was going to suggest that we could inspect the error code in `read_evm_actor` and return `None` if it's `22` which is `USR_UNHANDLED_MESSAGE`, which is a bit more specific than any other error that can happen. Since we only call it with these two methods, it's a pretty good indicator that we are dealing with an `ETHACCOUNT` actor, but won't mask things like non-existent accounts like the current workaround, and it's also not as difficult as I imagine it is to bring down the manifest CIDs and the actor state to compare.

**Comment by aakoshh** [comment]
Here's my version for the record: https://github.com/consensus-shipyard/ipc-monorepo/pull/511

**Comment by maciejwitowski** [comment]
@raulk do we want to continue investing in [that Draft PR](https://github.com/consensus-shipyard/ipc-monorepo/pull/514) or is Akosh's solution good enough? (let's avoid keeping open PRs)

**Comment by raulk** [comment]
We do, since that's the stable way of handling these cases and other scenarios that depend on the actor type.
