### ISSUE TITLE
GatewayRouterFacet is over 24KiB

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc-monorepo#9]
The build is failing on the dev branch because this contract is slightly over 24KiB. Given the tiny margin, I think it makes more sense to invest a few cycles to optimise than to break this facet up at this stage?

```
| Contract                    | Size (kB) | Margin (kB) |
|-----------------------------|-----------|-------------|
[...]
| GatewayRouterFacet          | 24.663    | -0.087      |
[...]
```

**Comment by snissn** [comment]
WIP here https://github.com/consensus-shipyard/ipc-solidity-actors/pull/408
